name: "PHPUnit testing"
run-name: ${{ github.actor }} is testing with phpunit

on: [pull_request]

jobs:
  phpunit:
    runs-on: ubuntu-latest
        
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          tools: composer
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: composer install
      - run: vendor/bin/phpunit